manuall external approval v7

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,6 +16,11 @@ jobs:
     runs-on: ubuntu-latest
     if: github.event.inputs.approve == 'True' 
     steps:
+      - name: Validate Selection
+        if: github.event.inputs.approve != 'True'
+        run: |
+          echo "Approver did not accepted."
+          exit 1  # Fail the workflow if the user doesn't choose "True" or "False"
       - name: Checkout Code
         uses: actions/checkout@v3
 
